// <auto-generated />
namespace WebEFCodeFirts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class inicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202003191624561_inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
